language: node_js
sudo: false
node_js:
  - "stable"

env:
  global:
    - CODACY_PROJECT_TOKEN=36330f847fae430991bc63d48e9a7df1

services:
  - mongodb

before_script:
  - date --rfc-2822

script:
  - npm test
  - npm run lint
  - npm run test:coverage

# after_script:
#   - cat coverage/lcov.info | codacy-coverage